#!/bin/ansible-playbook -v
---
- hosts: localhost
  tasks:
        - name: Upgrade system
          apt:
                  upgrade: safe

        - name: Install must-have packages
          apt:
                  pkg:
                          - git
                          - vim
                          - i3
                          - python3
                          - python3-pip

        - name: Set configuration files
          copy:
                  src: ./vimrc
                  dest: ~/.vimrc
	  copy:
	  	  src: ./i3.conf
		  dest: ~/.config/i3/config
